version: "3"
services:
  db-mysql-service:
    image: mysql:5.7
    container_name: db-mysql-service
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - myapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: spring-enquete
      MYSQL_DATABASE: enquete
      MYSQL_USER: spring-enquete
      MYSQL_PASSWORD: spring-enquete
    ports:
      - "3307:3306"
  spring-boot-service:
    container_name: spring-boot-service
    networks:
      - myapp-mysql
    depends_on:
      - db-mysql-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=enquete
      - DATABASE_PASSWORD=spring-enquete
      - DATABASE_USER=spring-enquete
volumes:
  db_data:
networks:
  myapp-mysql: