# spring-boot-docker/docker-compose.yml
version: "3.7"
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: spring-enquete
      MYSQL_DATABASE: enquete
      MYSQL_USER: spring-enquete
      MYSQL_PASSWORD: spring-enquete
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  db_data: